version: "3.4"
services:
  corona-tracker:
    image: corona-test
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: corona
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root