version: "3.4"
services:
  corona-tracker:
    image: corona-tracker
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: corona
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db1:/var/lib/postgresql/data
volumes:
  db1: