CREATE SEQUENCE USER_TABLE_SEQ START 1;
CREATE SEQUENCE PERSON_SEQ START 1;
CREATE SEQUENCE STORE_SEQ START 1;
CREATE SEQUENCE HEALTH_UNITY_SEQ START 1;
CREATE SEQUENCE DIAGNOSED_SEQ START 1;
CREATE SEQUENCE VISITED_STORE_SEQ START 1;
